[package]
name = "hpm-rom-rt"
version = "0.1.0"
edition = "2021"
links = "hpm-rom-rt" # Prevent multiple versions of hpm-rom-rt being linked

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2"
