#![no_std]

#[repr(C)]
pub struct FirmwareInfo {
    size: u32,
    flags: u32,
    _reserved1: u32,
    load_addr: u32,
    _reserved2: u32,
    entry_point: u32,
    _reserved3: u32,
    hash: [u8; 64],
    _reserve4: u32,
}

extern "C" {
    fn main() -> !;
}

#[link_section = ".nor_cfg_option.offset"]
pub static OFFSET: unsafe extern "C" fn() -> ! = main;

#[link_section = ".nor_cfg_option.firmware_info"]
pub static FIRMWARE_INFO: FirmwareInfo = FirmwareInfo {
    size: 0x90abcdef,
    flags: 0,
    _reserved1: 0,
    load_addr: 0,
    _reserved2: 0,
    entry_point: 0,
    _reserved3: 0,
    hash: [0; 64],
    _reserve4: 0,
};

#[link_section = ".nor_cfg_option.text_dummy"]
pub extern "C" fn text_dummy() {}

#[export_name = "_start"]
pub extern "C" fn start() {
    // todo: this function should be generated by macro
    // initialize environment and then call main function
    unsafe { main() }
}
