[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.11.0"
panic-halt = "0.2.0"
hpm-ral = { path = "../..", features = ["hpm6750"] }
hpm-bootheader = { path = "../../bootheader" }
hpm6750evkmini = { path = "../hpm6750evkmini" }
