[package]
name = "blink"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"
hpm-ral = { path = "../..", features = ["hpm6750"] }
hpm-rom-rt = { path = "../../hpm-rom-rt" }
hpm6750evkmini = { path = "../hpm6750evkmini" }
